#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path');
const REGISTRY='_meta/ownership.json',CATALOG='_meta/ownership-catalog.md';
const KINDS=new Set(['master','mixed','navigation','projection','generated','baseline','archive','tool']);
const EDITS=new Set(['manual','generated','review-refresh','frozen','mixed']);
const object=x=>x!==null&&typeof x==='object'&&!Array.isArray(x);
const text=x=>typeof x==='string'&&x.trim().length>0;
const own=(o,k)=>object(o)&&Object.hasOwn(o,k);
function relative(p,folder=false){return typeof p==='string'&&(folder&&p==='.'||p.length>0&&p===p.trim()&&!/[\\:\x00-\x1f\x7f]/.test(p)&&!p.startsWith('/')&&p.split('/').every(x=>x&&x!=='.'&&x!=='..')&&path.posix.normalize(p)===p);}
function assertRoot(input){if(!text(input))throw Error('A documentation directory is required');const root=path.resolve(input);let cursor=root;while(true){const st=fs.lstatSync(cursor);if(st.isSymbolicLink())throw Error('Symlink path component is not supported: '+cursor);if(cursor===root&&!st.isDirectory())throw Error('Documentation root is not a directory');const parent=path.dirname(cursor);if(parent===cursor)break;cursor=parent;}return root;}
function inventory(input){const root=assertRoot(input),files=[],folders=['.'],seen=new Map();function walk(rel){for(const entry of fs.readdirSync(path.join(root,rel),{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name))){const p=rel?rel+'/'+entry.name:entry.name;if(!relative(p))throw Error('Unsupported documentation path: '+p);const key=p.toLowerCase();if(seen.has(key))throw Error('Case-colliding paths: '+seen.get(key)+' / '+p);seen.set(key,p);const stat=fs.lstatSync(path.join(root,p));if(stat.isSymbolicLink())throw Error('Symlink is not permitted: '+p);if(stat.isDirectory()){folders.push(p);walk(p);}else if(stat.isFile())files.push(p);else throw Error('Special filesystem object is not permitted: '+p);}}walk('');return {files:files.sort(),folders:folders.sort()};}
function validate(reg,inv){const errors=[];if(!object(reg))return ['Registry must be an object'];if(!object(inv)||!Array.isArray(inv.files)||!Array.isArray(inv.folders)||!inv.files.every(x=>relative(x))||!inv.folders.every(x=>relative(x,true)))return ['Inventory must contain normalized file and folder arrays'];
 if(new Set(inv.files).size!==inv.files.length||new Set(inv.folders).size!==inv.folders.length)errors.push('Inventory contains duplicate paths');
 if(reg.schemaVersion!==1)errors.push('Unsupported schemaVersion');
 const roles=object(reg.roles)?reg.roles:{},external=object(reg.externalSources)?reg.externalSources:{};
 if(!object(reg.roles)||!Object.keys(roles).length)errors.push('roles must be a nonempty object');for(const [id,r] of Object.entries(roles))if(!text(id)||!object(r)||!text(r.label))errors.push('Invalid role metadata: '+id);
 if(!object(reg.externalSources))errors.push('externalSources must be an object');for(const [id,x] of Object.entries(external))if(!/^@[A-Za-z0-9][A-Za-z0-9._-]*$/.test(id)||!object(x)||!text(x.description))errors.push('Invalid external source: '+id);
 if(!Array.isArray(reg.files))errors.push('files must be an array');if(!Array.isArray(reg.folders))errors.push('folders must be an array');
 const records=Array.isArray(reg.files)?reg.files:[],dirs=Array.isArray(reg.folders)?reg.folders:[],byPath=new Map(),claims=new Map(),casePaths=new Map(),fileSet=new Set(inv.files),dirSet=new Set(inv.folders);
 const stringArray=(v,label)=>{if(!Array.isArray(v)||!v.every(text)){errors.push(label+' must be an array of nonempty strings');return [];}if(new Set(v).size!==v.length)errors.push(label+' contains duplicates');return v;};
 for(const r of records){if(!object(r)){errors.push('File record must be an object');continue;}const p=r.path;if(!relative(p)){errors.push('Invalid file path: '+String(p));continue;}const lower=p.toLowerCase();if(casePaths.has(lower))errors.push('Duplicate/case-colliding file: '+p);casePaths.set(lower,p);byPath.set(p,r);
  if(!fileSet.has(p))errors.push('Registered file missing: '+p);if(!own(roles,r.owner))errors.push('Unknown owner: '+p);if(!KINDS.has(r.kind))errors.push('Unknown kind: '+p);if(!EDITS.has(r.edit))errors.push('Invalid edit policy: '+p);
  for(const k of ['scope','editWhen','procedure'])if(!text(r[k]))errors.push('Missing '+k+': '+p);
  const owns=stringArray(r.owns,p+'.owns'),upstream=stringArray(r.upstream,p+'.upstream');
  if(r.kind==='generated'&&(r.edit!=='generated'||owns.length||!upstream.length))errors.push('Generated output requires edit=generated, upstream and no owned facts: '+p);
  if(r.kind==='projection'&&(owns.length||!upstream.length||!['manual','generated','review-refresh'].includes(r.edit)))errors.push('Projection requires upstream, no owned facts and a refresh policy: '+p);
  if(r.kind==='baseline'&&r.edit!=='review-refresh')errors.push('Baseline requires edit=review-refresh: '+p);
  if(['master','navigation','tool'].includes(r.kind)&&r.edit!=='manual')errors.push('Master/navigation/tool require edit=manual: '+p);
  if(r.kind==='mixed'&&(r.edit!=='mixed'||!object(r.fields)||!Object.keys(r.fields).length))errors.push('Mixed source requires edit=mixed and explicit fields: '+p);
  if(own(r,'fields')){if(!object(r.fields)||!Object.keys(r.fields).length)errors.push('Invalid field ownership: '+p);else for(const [field,rule] of Object.entries(r.fields))if(!text(field)||!text(rule))errors.push('Invalid field ownership: '+p+'.'+field);if(r.kind!=='mixed')errors.push('Field ownership is only allowed for mixed sources: '+p);}
  if(r.edit==='mixed'&&r.kind!=='mixed')errors.push('edit=mixed requires kind=mixed: '+p);
  if(r.kind==='archive'&&(r.edit!=='frozen'||owns.length))errors.push('Archive must be frozen and own no current facts: '+p);
  if(['master','mixed','navigation','tool','baseline'].includes(r.kind)&&!owns.length)errors.push('Missing owned scope: '+p);
  if(r.edit==='generated'&&owns.length)errors.push('Generated edit policy cannot own facts: '+p);
  for(const claim of owns){if(claim!==claim.trim())errors.push('Owned claim has surrounding whitespace: '+p);const key=claim.trim();if(claims.has(key))errors.push('Duplicate master claim '+key+': '+claims.get(key)+' / '+p);else claims.set(key,p);}
  for(const ref of upstream){if(ref.startsWith('@')){if(!own(external,ref))errors.push('Unknown external source '+ref+' in '+p);}else if(!relative(ref))errors.push('Invalid upstream path '+ref+' in '+p);}
 }
 for(const p of inv.files)if(!byPath.has(p))errors.push('Unclassified file: '+p);
 const byDir=new Map(),dirCases=new Set();for(const d of dirs){if(!object(d)){errors.push('Folder record must be an object');continue;}if(!relative(d.path,true)){errors.push('Invalid folder path: '+String(d.path));continue;}if(dirCases.has(d.path.toLowerCase()))errors.push('Duplicate/case-colliding folder: '+d.path);dirCases.add(d.path.toLowerCase());byDir.set(d.path,d);if(!dirSet.has(d.path))errors.push('Registered folder missing: '+d.path);if(!own(roles,d.owner)||!text(d.scope))errors.push('Invalid folder ownership: '+d.path);}
 for(const p of inv.folders)if(!byDir.has(p))errors.push('Unclassified folder: '+p);
 for(const [p,r] of byPath)for(const ref of Array.isArray(r.upstream)?r.upstream:[])if(typeof ref==='string'&&!ref.startsWith('@')&&relative(ref)&&!byPath.has(ref))errors.push('Missing upstream '+ref+' in '+p);
 // Kahn traversal avoids recursive stack exhaustion on large, malformed dependency graphs.
 const degree=new Map([...byPath.keys()].map(k=>[k,0])),users=new Map([...byPath.keys()].map(k=>[k,[]]));for(const [p,r]of byPath)for(const ref of Array.isArray(r.upstream)?r.upstream:[])if(byPath.has(ref)){degree.set(p,degree.get(p)+1);users.get(ref).push(p);}const queue=[...degree].filter(([,n])=>n===0).map(([p])=>p);for(let i=0;i<queue.length;i++)for(const p of users.get(queue[i])){degree.set(p,degree.get(p)-1);if(degree.get(p)===0)queue.push(p);}if(queue.length!==byPath.size)errors.push('Dependency cycle: '+[...degree].filter(([,n])=>n>0).map(([p])=>p).join(', '));
 return errors;
}
function render(reg){const esc=x=>String(x).replace(/\\/g,'\\\\').replace(/[|\r\n]/g,c=>c==='|'?'\\|':' '),link=p=>'['+esc(p).replace(/[\[\]]/g,'\\$&')+'](../'+p.split('/').map(encodeURIComponent).join('/')+')';let out='# Ownership catalog — generated\n\nDo not edit this file. Source: [ownership.json](ownership.json). Run `verify-docs.cjs --docs <path> --write-catalog` after an intentional registry update. Roles describe responsibilities, not individuals. This catalog validates declared ownership; semantic completeness requires review.\n\n## Folders\n\n| Folder | Responsible role | Scope |\n|---|---|---|\n';for(const d of [...reg.folders].sort((a,b)=>a.path.localeCompare(b.path)))out+='| `'+esc(d.path)+'` | '+esc(reg.roles[d.owner].label)+' | '+esc(d.scope)+' |\n';
 out+='\n## Files\n\n';for(const r of [...reg.files].sort((a,b)=>a.path.localeCompare(b.path))){const usedBy=reg.files.filter(x=>x.upstream.includes(r.path)).map(x=>x.path).sort();out+='### '+esc(r.path)+'\n\n- File: '+link(r.path)+'\n- Role: '+esc(reg.roles[r.owner].label)+'; kind: `'+r.kind+'`; edit: `'+r.edit+'`\n- Scope: '+esc(r.scope)+'\n- Owns: '+(r.owns.length?r.owns.map(esc).join('; '):'no independent current facts')+'\n- Upstream: '+(r.upstream.length?r.upstream.map(x=>x.startsWith('@')?esc(x)+' — '+esc(reg.externalSources[x].description):link(x)).join('; '):'none')+'\n- Used by: '+(usedBy.length?usedBy.map(link).join('; '):'none declared')+'\n- Edit when: '+esc(r.editWhen)+'\n- Procedure: '+esc(r.procedure)+'\n';if(r.fields)out+='- Field ownership: '+Object.entries(r.fields).map(([k,v])=>'`'+esc(k)+'`: '+esc(v)).join('; ')+'\n';out+='\n';}return out;}
function check(input,options={}){if(!object(options))return {status:"FAIL",errors:["Options must be an object"]};const errors=[];let root,inv,reg;try{root=assertRoot(input);inv=inventory(root);reg=JSON.parse(fs.readFileSync(path.join(root,REGISTRY),'utf8').replace(/^\uFEFF/,''));}catch(e){return {status:'FAIL',errors:[e.message]};}
 const missingCatalog=!inv.files.includes(CATALOG);const validationInventory=options.writeCatalog&&missingCatalog?{...inv,files:[...inv.files,CATALOG].sort()}:inv;errors.push(...validate(reg,validationInventory));if(!errors.length&&(!reg.files.some(r=>r.path===REGISTRY)||!reg.files.some(r=>r.path===CATALOG&&r.kind==='generated'&&r.upstream.includes(REGISTRY))))errors.push('Registry and generated catalog must be explicitly registered; catalog must depend on registry');
 let selected;if(options.file!==undefined){if(!relative(options.file))errors.push('Invalid --file path');else{selected=Array.isArray(reg?.files)?reg.files.find(r=>object(r)&&r.path===options.file):undefined;if(!selected)errors.push('File not registered: '+options.file);}}
 if(!errors.length){const expected=render(reg);if(options.writeCatalog){try{ // Recheck all paths immediately before the only permitted write.
 inventory(root);const target=path.join(root,CATALOG);if(fs.existsSync(target)&&fs.lstatSync(target).nlink>1)throw Error('Refusing to overwrite a hard-linked catalog');fs.writeFileSync(target,expected,{encoding:'utf8',flag:'w'});}catch(e){errors.push(e.message);}}
 if(!errors.length){try{if(!fs.existsSync(path.join(root,CATALOG)))errors.push('Catalog missing; run --write-catalog');else if(fs.readFileSync(path.join(root,CATALOG),'utf8')!==expected)errors.push('Catalog stale; run --write-catalog');}catch(e){errors.push(e.message);}}}
 return {status:errors.length?'FAIL':'PASS',files:validationInventory.files.length,folders:inv.folders.length,errors,...(selected?{record:selected,usedBy:reg.files.filter(r=>object(r)&&Array.isArray(r.upstream)&&r.upstream.includes(selected.path)).map(r=>r.path)}:{})};}
function main(){const args=process.argv.slice(2),options={};let docs;for(let i=0;i<args.length;i++){const a=args[i];if(a==='--write-catalog'){if(options.writeCatalog)throw Error('Duplicate --write-catalog');options.writeCatalog=true;}else if(a==='--docs'||a==='--file'){if(!args[i+1]||args[i+1].startsWith('--'))throw Error('Missing value for '+a);if(a==='--docs'){if(docs!==undefined)throw Error('Duplicate --docs');docs=args[++i];}else{if(options.file!==undefined)throw Error('Duplicate --file');options.file=args[++i];}}else throw Error('Unknown argument '+a);}if(!docs)throw Error('Usage: verify-docs.cjs --docs PATH [--write-catalog] [--file REL]');const result=check(docs,options);console.log(JSON.stringify(result,null,2));if(result.status!=='PASS')process.exitCode=1;}
if(require.main===module){try{main();}catch(e){console.error(e.message);process.exitCode=1;}}
module.exports={inventory,validate,render,check,REGISTRY,CATALOG};

